### ISSUE TITLE
Enable GC logging

### ISSUE THREAD

**Issue by uschi2000** [palantir/gradle-java-distribution#126]
Something like

```
  launcherCustom:
    configType: java
    configVersion: 1
    jvmOpts:
      - '-XX:+PrintGCDateStamps'
      - '-XX:+PrintGCDetails'
      - '-XX:-TraceClassUnloading'
      - '-XX:+UseGCLogFileRotation'
      - '-XX:GCLogFileSize=10M'
      - '-XX:NumberOfGCLogFiles=10'
      - '-Xloggc:var/log/{{product_name}}.gc.log'
      - '-verbose:gc'
```
