### ISSUE TITLE
`[service-name]` bash start script does not use JVM options from `launcher-custom.yml`

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-java-distribution#139]
I'd like to run a custom dropwizard command (`migrate`) to do migrations, that needs the JVM trustStore system property to be set.

Since I can't use `init.sh` to run `migrate`, I tried to use the `[service-name]` bash start script, however, this did not pick up the JVM arguments I'd set in `launcher-custom.yml`. 

```yml
  launcherCustom:
    configType: java
    configVersion: 1
    jvmOpts:
      - '-Djavax.net.ssl.trustStore=XXX'
```

Is this a reasonable approach to take or am I going about this the wrong way?
