### ISSUE TITLE
Adding plugin jars to the runtime classpath

### ISSUE THREAD

**Issue by Xenorith** [palantir/gradle-java-distribution#57]
Is there a way to configure the classpath of the application script to include a specified plugins directory? I'd like to add var/plugins/\* to the end of the classpath.

**Comment by markelliot** [comment]
It'd have to be done at build time by specifying those jars on your project's runtime classpath.

**Comment by Xenorith** [comment]
But plugin jars don't exist when the project is being built; they are added after the distribution has been deployed but before server startup.

**Comment by markelliot** [comment]
I understand, but that's not really the model for which this system was designed. Our spec says basically that distributions that include plugins at runtime (rather than at build time) do so by treating the plugins as data, and must manually manage their loading. It also seems like a poor experience to require a restart of your system to use an after-install deployed plugin.

**Comment by markelliot** [comment]
I think you should be able to modify your Gradle runtime classpath to include `var/plugins` as an entry, and that it should make it through the build pipeline. There's risk to working in this setup, notably that there's no guarantee of the jar ordering.

**Comment by ash211** [comment]
Mark's suggestion to modify the Gradle runtime classpath doesn't work:

gradle change:

```
 dependencies {
+    runtime files('../../var/conf/')
+    runtime files('../share/s3e/*')
+    runtime files('../../var/plugins/*')
+
```

Resulting `launcher-static.yml`:

```
  configType: "java"
  configVersion: 1
  mainClass: "com.palantir.X.Y.Z"
  javaHome: ""
  classpath:
  - "service/lib/XYZ.jar"
  - "service/lib/conf"
  - "service/lib/*"
  - "service/lib/*"
  - "service/lib/XYZ.jar"
  - "service/lib/XYZ.jar"
...
```

I think the problem is that this relativization code forces classpaths to always start with `service/lib/` and attempting to break out of that with directory traversal like `../../var/plugins/*` doesn't work.

For the service I'm working on to upgrade to a version of gjd using the go launcher (and not the security-vulnerable bash launcher), I'm going to have to modify `launcher-static.yml` after it's rendered by this plugin to force those classpath entries in.

Is this the best we can do here?
